server:
  port: 8080

name: zhangsan

person:
  name: zhangsan
  age: 20
  address:
    - beijing
    - shanghai

# 对象行内写法
person2: {name: zhangsan,age: 20}

# 数组
address:
  - beijing
  - shanghai

# 数组行内写法
address2: [beijing,shanghai]

# 纯量：单个的、不可再分的值
msg1: 'hello \n world'
msg2: "hello \n world"